export enum ActionType {
  GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR",

  GET_CART_PRODUCTS_REQUEST = "GET_CART_PRODUCTS_REQUEST",
  GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS",
  GET_CART_PRODUCTS_ERROR = "GET_CART_PRODUCTS_ERROR",
}
